### ISSUE TITLE
image search does not work

### ISSUE THREAD

**Issue by NilsMosser** [fraction/oasis#535] opened 2020-11-27 11:29 UTC
## What's the problem you want solved?
![grafik](https://user-images.githubusercontent.com/43217164/100444637-061cf000-30ac-11eb-8385-ddfaac3973be.png)
Whenever I type anything here and hit enter this happens:
![grafik](https://user-images.githubusercontent.com/43217164/100444671-1c2ab080-30ac-11eb-8f66-e5aac4c59477.png)
Please fix this. It is rather annoying. Thanks a million!!! Stay safe
## Is there a solution you'd like to recommend?

I have no clue

**Comment by black-puppydog** [comment] 2020-11-27 12:34
Hi Nils,
is this running the last release of oasis, or which version are you using there?

**Comment by NilsMosser** [comment] 2020-11-27 15:18
> 
> 
> Hi Nils,
> is this running the last release of oasis, or which version are you using there?

# I am running version 2.17.0 Is that the latest version?
## If not how can I update?

**Comment by christianbundy** [comment] 2020-11-27 18:08
Are you running Patchwork in the background? I think the image search might only work if Oasis is running the server, if it's piggy-backing on Patchwork I don't think it'll work. :/

**Comment by christianbundy** [comment] 2020-11-27 18:09
Closing as a duplicate of #432. :tada:

**Closed by christianbundy** 2020-11-27 18:09 UTC
