### ISSUE TITLE
oasis does not honor custom caps.shs when connecting to external ssb-server

### ISSUE THREAD

**Issue by khimaros** [fraction/oasis#351] opened 2020-03-25 01:37 UTC
## What's the problem you want solved?
oasis does not connect to ssb-server if the server is configured with non-default `caps.shs`

To reproduce, add a custom `"caps": { "shs": "<random string>" }` to `~/.ssb/config`, launch `ssb-server start` and then launch oasis on the same device.

## Is there a solution you'd like to recommend?
connect to the ssb-server with custom `caps.shs` defined in .ssb/config

## What version or commit of Oasis are you using?
git hash https://github.com/fraction/oasis/commit/519fc499ac78e273cada79b366fd3b80249afb37

**Comment by christianbundy** [comment] 2020-03-25 01:55
CONFIRMED. The problem is that we're doing this:

- Attempt connection to server using Unix socket address.
- If that fails, try starting an SSB server.

Instead, we should also be doing this step between those:

- If original attempt fails, attempt connection via `localhost:8008` address instead.

**Comment by khimaros** [comment] 2020-03-29 18:31
I think this issue could be resolved by a bit of documentation if you think this use case is worth supporting and encouraging.

My goal was to deploy ssb-server and a Wi-Fi acccess point on an RPi4. I had a few requirements:

- use oasis as an administrative frontend for the pub
- the server should automatically peer with/follow anyone on local network
- use private caps to avoid accidental peering w/ public nodes

Discoveries from this experiment:

1. oasis makes a great web based administrative interface for pubs!
1. unix socket must be explicitly enabled in ~/.ssb/config eg. `"unix": [ {"scope": "device", "transform": "noauth" }]` in order for oasis to connect to the running ssb-server. this control interface is not part of the default ssb-config
1. for oasis to work happily with the custom ssb-server, you must load `ssb-about`, `ssb-backlinks`, and `ssb-search`. fortunately, these can be loaded via ~/.ssb/config

Discoveries not specific to oasis:

1. ssb-server configured with `"net": { "scope": "local", "host": "172.16.10.1" }` does not limit gossip to the inet interface or subnet of the defined host: 172.16.10.1 (gossip leaks out onto other interfaces on the machine). it seems to behave identically to "scope": "public".
1. private caps are simple enough to configure, caps.sign and caps.invite should be defined to avoid certain forms of data leak.
1. ssb-clingy fulfills the auto peer/follow requirement. it can be installed via npm into ~/.ssb/ and loaded via ~/.ssb/config
1. a lot of documentation, especially documentation related to running a pub, still refers to sbot and scuttlebot instead of ssb-server
1. ssb-server plugins.install and plugins.enable, also mentioned in a lot of documentation, do not seem to work. it is often necessary to `cd ~/.ssb && npm install` plugins and add them to ~/.ssb/config by hand, eg. `"plugins": { "ssb-about": true }`
1. ssb-conn and ssb-lan are [not compatible with ssb-plugins](https://gitlab.com/staltz/secret-stack-decorators/-/issues/1), thus can't be enabled in ssb-server via ~/.ssb/config without modification.
1. ssb-local is also not compatible with ssb-plugins. The simple fix is to add `manifest: {}` to module exports in `ssb-local/index.js`. I'm not sure if there is a more idiomatic solution. fortunately, this is not a problem with ssb-server since it is enabled by default.
1. manyverse must be built from source to enable alternative caps
1. (ssb-conn **and** ssb-lan) **or** ssb-local plugins must be loaded into ssb-server for local network peer discovery to work.

**Comment by christianbundy** [comment] 2020-03-29 19:21
> I think this issue could be resolved by a bit of documentation if you think this use case is worth supporting and encouraging.

Yes! I would love any docs you'd like to add, please feel welcome to add any info you'd like to see in this repo. There's `with-docker.md` and `with-systemd.md`, please feel free to edit existing documents or add your own. .`Btw, you *may* be interested in [SSB-Daemon](https://github.com/fraction/ssb-daemon), which loads all of the "modern" plugins that Oasis uses.

(My guess is that #352 will be merged in the next few days, once a maintainer has time/energy/interest to check it out.)

**Closed** 2020-04-02 17:50 UTC
Labels: bug
