### ISSUE TITLE
Add support for gatherings

### ISSUE THREAD

**Issue by Powersource** [fraction/oasis#554] opened 2020-12-14 21:06 UTC
## What's the problem you want solved?

I can view/edit/attend gatherings in patchwork but not in oasis so I miss stuff that my friends are up to

## Is there a solution you'd like to recommend?

Implement support for them in oasis

**Comment by black-puppydog** [comment] 2020-12-15 18:30
Closing as duplicate of #268 😛

**Closed by black-puppydog** 2020-12-15 18:30 UTC
Labels: enhancement, patchwork parity
